### DISCUSSION TITLE
Having Issues with "publish-report: false"

### DISCUSSION THREAD

**Discussion by plumocracy** [godot-gdunit-labs/gdUnit4-action#70] [Q&A] [answered]
Hey! I'm having some issues with report publishing. If I leave it enabled my CI/CD will fail due to an http error `HttpError: Resource not accessible by integration` and if I try to disable it with `publish-report: false` I get a warning about unexpected inputs and the report attempts to publish anyway. Any guidance on this would rock! Thanks :)

Full src for my runner: 

```
name: GdUnit4 Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: '4.4'
          godot-status: 'stable'
          paths: 'res://src/test'
          publish-report: false
````

**Comment by MikeSchulze** [comment]
You should use the latest version.
` MikeSchulze/gdunit4-action@v1.1.5`

**Reply by plumocracy** [reply]
I worked around it on the version I had originally by adding
```
permissions:
  id-token: write
  contents: read
  checks: write
```
to the workflow. Updated to latest and all is well. I didn't realize the readme had an old version listed. I'll submit a PR to update it to reflect latest to curb confusion
