### DISCUSSION TITLE
Confused about warning message meaning.

### DISCUSSION THREAD

**Discussion by plumocracy** [godot-gdunit-labs/gdUnit4-action#79] [Q&A] [answered]
Hey,

I'm working on getting CI integrated with a Godot C# project that I am working on. Whenever I run the github action (a modified version of the [template given on the wiki](https://mikeschulze.github.io/gdUnit4/faq/ci/) I get this warning message.

`It was recognized that GdUnit4 is running in a test environment, therefore the GdUnit4 plugin will not be executed!`

It seems something is stopping my tests from running, as I intentionally merged a failing test and the CI succeeds without reporting any issues. I'm likely missing something in my .yml, but I've scrubbed the github docs and not sure where I'm going wrong here. Any help would be appreciated! 

Thanks!

```
name: CI-Tests
run-name: ${{ github.head_ref || github.ref_name }}-ci-Tests

on:
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.md'
  workflow_dispatch:


concurrency:
  group: CI-Tests${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "CI Unit Test"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: MikeSchulze/gdUnit4-action@v1
        with:
          godot-version: '4.4.1'
          godot-status: 'stable'
          godot-net: true
          paths: |
            res://tests/
          timeout: 5
          report-name: test_report.xml     
 ```
